import { contentText, type Model, type Models, type RetryCallbacks, type RetryPolicy, type Usage } from "@rigyn/models";
import type { AgentMessage } from "../../types.js";
import { convertToLlm, createBranchSummaryMessage, createCompactionSummaryMessage, createCustomMessage } from "../messages.js";
import type { Result, Session, SessionTreeEntry } from "../types.js";
import { BranchSummaryError, err, ok, SessionError } from "../types.js";
import { completeSimpleWithRetries, estimateTokens, SUMMARIZATION_SYSTEM_PROMPT } from "./compaction.js";
import { computeFileLists, createFileOps, extractFileOpsFromMessage, formatFileOperations, serializeConversation, type FileOperations } from "./utils.js";
export interface BranchSummaryDetails { readFiles: string[]; modifiedFiles: string[]; }
export interface BranchPreparation { messages: AgentMessage[]; fileOps: FileOperations; totalTokens: number; }
export interface CollectEntriesResult { entries: SessionTreeEntry[]; commonAncestorId: string | null; }
export interface GenerateBranchSummaryOptions { models: Models; model: Model; signal: AbortSignal; customInstructions?: string; replaceInstructions?: boolean; reserveTokens?: number; retry?: RetryPolicy; callbacks?: RetryCallbacks; }
export async function collectEntriesForBranchSummary(session: Session, oldLeafId: string | null, targetId: string): Promise<CollectEntriesResult> { if (!oldLeafId) return { entries: [], commonAncestorId: null }; const oldPath = new Set((await session.getBranch(oldLeafId)).map((entry) => entry.id)); const targetPath = await session.getBranch(targetId); let commonAncestorId: string | null = null; for (let index = targetPath.length - 1; index >= 0; index--) if (oldPath.has(targetPath[index]!.id)) { commonAncestorId = targetPath[index]!.id; break; } const entries: SessionTreeEntry[] = []; let cursor: string | null = oldLeafId; while (cursor && cursor !== commonAncestorId) { const entry = await session.getEntry(cursor); if (!entry) throw new SessionError("invalid_session", `Entry ${cursor} not found`); entries.push(entry); cursor = entry.parentId; } return { entries: entries.reverse(), commonAncestorId }; }
function message(entry: SessionTreeEntry): AgentMessage | undefined { if (entry.type === "message") return entry.message.role === "toolResult" ? undefined : entry.message; if (entry.type === "custom_message") return createCustomMessage(entry.customType, entry.content, entry.display, entry.details, entry.timestamp); if (entry.type === "branch_summary") return createBranchSummaryMessage(entry.summary, entry.fromId, entry.timestamp); if (entry.type === "compaction") return createCompactionSummaryMessage(entry.summary, entry.tokensBefore, entry.timestamp); return undefined; }
export function prepareBranchEntries(entries: SessionTreeEntry[], tokenBudget = 0): BranchPreparation { const messages: AgentMessage[] = []; const fileOps = createFileOps(); let totalTokens = 0; for (const entry of entries) if (entry.type === "branch_summary" && !entry.fromHook && entry.details) { const details = entry.details as BranchSummaryDetails; for (const path of details.readFiles ?? []) fileOps.read.add(path); for (const path of details.modifiedFiles ?? []) fileOps.edited.add(path); } for (let index = entries.length - 1; index >= 0; index--) { const candidate = message(entries[index]!); if (!candidate) continue; extractFileOpsFromMessage(candidate, fileOps); const tokens = estimateTokens(candidate); if (tokenBudget > 0 && totalTokens + tokens > tokenBudget) { if ((entries[index]!.type === "compaction" || entries[index]!.type === "branch_summary") && totalTokens < tokenBudget * 0.9) { messages.unshift(candidate); totalTokens += tokens; } break; } messages.unshift(candidate); totalTokens += tokens; } return { messages, fileOps, totalTokens }; }
export async function generateBranchSummary(entries: SessionTreeEntry[], options: GenerateBranchSummaryOptions): Promise<Result<{ summary: string; usage?: Usage; readFiles: string[]; modifiedFiles: string[] }, BranchSummaryError>> { const prepared = prepareBranchEntries(entries, (options.model.contextWindow || 128000) - (options.reserveTokens ?? 16384)); if (!prepared.messages.length) return ok({ summary: "No content to summarize", readFiles: [], modifiedFiles: [] }); const standard = "Summarize this abandoned conversation branch with goal, constraints, completed and unfinished work, blockers, decisions, and next steps."; const instructions = options.replaceInstructions && options.customInstructions ? options.customInstructions : options.customInstructions ? `${standard}\n\nAdditional focus: ${options.customInstructions}` : standard; const prompt = `<conversation>\n${serializeConversation(convertToLlm(prepared.messages))}\n</conversation>\n\n${instructions}`; const response = await completeSimpleWithRetries(options.models, options.model, { systemPrompt: SUMMARIZATION_SYSTEM_PROMPT, messages: [{ role: "user", content: [{ type: "text", text: prompt }], timestamp: Date.now() }] }, { signal: options.signal, maxTokens: 2048 }, options.retry, options.callbacks); if (response.stopReason === "aborted") return err(new BranchSummaryError("aborted", response.errorMessage || "Branch summary aborted")); if (response.stopReason === "error") return err(new BranchSummaryError("summarization_failed", `Branch summary failed: ${response.errorMessage || "Unknown error"}`)); const files = computeFileLists(prepared.fileOps); const summary = `The user explored another conversation branch before returning here.\nSummary of that exploration:\n\n${contentText(response.content)}${formatFileOperations(files.readFiles, files.modifiedFiles)}`; return ok({ summary: summary || "No summary generated", usage: response.usage, ...files }); }
export type { FileOperations } from "./utils.js";
