import { contentText, type Message } from "@rigyn/models";
import type { AgentMessage } from "../../types.js";
export interface FileOperations { read: Set<string>; written: Set<string>; edited: Set<string>; }
export const createFileOps = (): FileOperations => ({ read: new Set(), written: new Set(), edited: new Set() });
export function extractFileOpsFromMessage(message: AgentMessage, ops: FileOperations): void { if (message.role !== "assistant") return; for (const part of message.content) { if (part.type !== "toolCall" || typeof part.arguments.path !== "string") continue; if (part.name === "read") ops.read.add(part.arguments.path); else if (part.name === "write") ops.written.add(part.arguments.path); else if (part.name === "edit") ops.edited.add(part.arguments.path); } }
export function computeFileLists(ops: FileOperations): { readFiles: string[]; modifiedFiles: string[] } { const modified = new Set([...ops.written, ...ops.edited]); return { readFiles: [...ops.read].filter((path) => !modified.has(path)).sort(), modifiedFiles: [...modified].sort() }; }
export function formatFileOperations(readFiles: string[], modifiedFiles: string[]): string { const blocks: string[] = []; if (readFiles.length) blocks.push(`<read-files>\n${readFiles.join("\n")}\n</read-files>`); if (modifiedFiles.length) blocks.push(`<modified-files>\n${modifiedFiles.join("\n")}\n</modified-files>`); return blocks.length ? `\n\n${blocks.join("\n\n")}` : ""; }
function safe(value: unknown): string { try { return JSON.stringify(value) ?? "undefined"; } catch { return "[unserializable]"; } }
export function serializeConversation(messages: Message[]): string { const result: string[] = []; for (const message of messages) { if (message.role === "user") { const text = contentText(message.content, ""); if (text) result.push(`[User]: ${text}`); } else if (message.role === "assistant") { const thought = message.content.filter((part) => part.type === "thinking").map((part) => part.type === "thinking" ? part.thinking : ""); const calls = message.content.filter((part) => part.type === "toolCall").map((part) => part.type === "toolCall" ? `${part.name}(${Object.entries(part.arguments).map(([key, value]) => `${key}=${safe(value)}`).join(", ")})` : ""); if (thought.length) result.push(`[Assistant thinking]: ${thought.join("\n")}`); const text = contentText(message.content); if (text) result.push(`[Assistant]: ${text}`); if (calls.length) result.push(`[Assistant tool calls]: ${calls.join("; ")}`); } else { const text = contentText(message.content, ""); if (text) result.push(`[Tool result]: ${text.length <= 2000 ? text : `${text.slice(0, 2000)}\n\n[... ${text.length - 2000} more characters truncated]`}`); } } return result.join("\n\n"); }
