import type { OAuthAuth, OAuthCredential } from "../types.js";
import { pollOAuthDeviceCodeFlow } from "./device-code.js";
import { requestJson, required } from "./http.js";
const clientId = Buffer.from("SXYxLmI1MDdhMDhjODdlY2ZlOTg=", "base64").toString("utf8");
const headers = { "user-agent": "GitHubCopilotChat/0.35.0", "editor-version": "vscode/1.107.0", "editor-plugin-version": "copilot-chat/0.35.0", "copilot-integration-id": "vscode-chat" };
function domain(value: string): string | undefined { if (!value.trim()) return undefined; try { return new URL(value.includes("://") ? value : `https://${value}`).hostname; } catch { throw new Error("Invalid enterprise domain"); } }
const urls = (host: string) => ({ device: `https://${host}/login/device/code`, token: `https://${host}/login/oauth/access_token`, copilot: `https://api.${host}/copilot_internal/v2/token` });
function baseUrl(token: string, enterprise?: string): string { const match = /proxy-ep=([^;]+)/u.exec(token)?.[1]; return match ? `https://${match.replace(/^proxy\./u, "api.")}` : enterprise ? `https://copilot-api.${enterprise}` : "https://api.individual.githubcopilot.com"; }
async function copilot(githubToken: string, enterprise?: string, signal?: AbortSignal): Promise<OAuthCredential> { const endpoint = enterprise ? urls(enterprise).copilot : "https://api.github.com/copilot_internal/v2/token"; const { body } = await requestJson(endpoint, { headers: { ...headers, authorization: `token ${githubToken}`, accept: "application/json" }, ...(signal ? { signal } : {}) }); const access = required(body, "token"); const expires = typeof body.expires_at === "number" ? body.expires_at * 1_000 : Date.now() + 25 * 60_000; return { type: "oauth", refresh: githubToken, access, expires: expires - 60_000, ...(enterprise ? { enterpriseUrl: enterprise } : {}) };
}
export const githubCopilotOAuth: OAuthAuth = { name: "GitHub Copilot", async login(interaction) { const enterprise = domain(await interaction.prompt({ type: "text", message: "Enterprise domain (leave blank for github.com)", placeholder: "company.example", ...(interaction.signal ? { signal: interaction.signal } : {}) })); const host = enterprise ?? "github.com"; const endpoints = urls(host); const started = await requestJson(endpoints.device, { method: "POST", headers: { accept: "application/json", "content-type": "application/x-www-form-urlencoded", "user-agent": headers["user-agent"] }, body: new URLSearchParams({ client_id: clientId, scope: "read:user" }), ...(interaction.signal ? { signal: interaction.signal } : {}) }); const deviceCode = required(started.body, "device_code"); const userCode = required(started.body, "user_code"); const verification = required(started.body, "verification_uri"); const interval = typeof started.body.interval === "number" ? started.body.interval : 5; const expires = typeof started.body.expires_in === "number" ? started.body.expires_in : 900; interaction.notify({ type: "device_code", userCode, verificationUri: verification, intervalSeconds: interval, expiresInSeconds: expires }); const githubToken = await pollOAuthDeviceCodeFlow<string>({ intervalSeconds: interval, expiresInSeconds: expires, waitBeforeFirstPoll: true, ...(interaction.signal ? { signal: interaction.signal } : {}), async poll() { const response = await fetch(endpoints.token, { method: "POST", headers: { accept: "application/json", "content-type": "application/x-www-form-urlencoded", "user-agent": headers["user-agent"] }, body: new URLSearchParams({ client_id: clientId, device_code: deviceCode, grant_type: "urn:ietf:params:oauth:grant-type:device_code" }), ...(interaction.signal ? { signal: interaction.signal } : {}) }); const body = await response.json() as Record<string, unknown>; if (typeof body.access_token === "string") return { status: "complete", value: body.access_token }; if (body.error === "authorization_pending") return { status: "pending" }; if (body.error === "slow_down") return { status: "slow_down", ...(typeof body.interval === "number" ? { intervalSeconds: body.interval } : {}) }; return { status: "failed", message: typeof body.error_description === "string" ? body.error_description : `GitHub device flow failed: ${String(body.error ?? response.status)}` }; } }); return copilot(githubToken, enterprise, interaction.signal); }, refresh(value, signal) { return copilot(value.refresh, typeof value.enterpriseUrl === "string" ? value.enterpriseUrl : undefined, signal); }, async toAuth(value) { const enterprise = typeof value.enterpriseUrl === "string" ? value.enterpriseUrl : undefined; return { apiKey: value.access, baseUrl: baseUrl(value.access, enterprise), headers: { ...headers, authorization: `Bearer ${value.access}` } }; } };
