import type { OAuthAuth, OAuthCredential } from "../types.js";
import { authorizationInput, credential, requestJson, required } from "./http.js";
import { pollOAuthDeviceCodeFlow } from "./device-code.js";
import { generatePKCE } from "./pkce.js";
const clientId = "app_EMoamEEZ73f0CkXaXp7hrann"; const base = "https://auth.openai.com"; const authorize = `${base}/oauth/authorize`; const token = `${base}/oauth/token`; const deviceStart = `${base}/api/accounts/deviceauth/usercode`; const devicePoll = `${base}/api/accounts/deviceauth/token`; const browserRedirect = "http://localhost:1455/auth/callback"; const deviceRedirect = `${base}/deviceauth/callback`; const scope = "openid profile email offline_access";
function account(access: string): string | undefined { try { const payload = JSON.parse(Buffer.from(access.split(".")[1] ?? "", "base64url").toString("utf8")) as Record<string, unknown>; const auth = payload["https://api.openai.com/auth"]; return auth && typeof auth === "object" && typeof (auth as Record<string, unknown>).chatgpt_account_id === "string" ? (auth as Record<string, unknown>).chatgpt_account_id as string : undefined; } catch { return undefined; } }
function withAccount(value: OAuthCredential): OAuthCredential { const accountId = account(value.access); return accountId ? { ...value, accountId } : value; }
async function exchange(code: string, verifier: string, redirect: string, signal?: AbortSignal): Promise<OAuthCredential> { const { body } = await requestJson(token, { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ grant_type: "authorization_code", client_id: clientId, code, code_verifier: verifier, redirect_uri: redirect }), ...(signal ? { signal } : {}) }); return withAccount(credential(body)); }
async function refresh(value: OAuthCredential, signal?: AbortSignal): Promise<OAuthCredential> { const { body } = await requestJson(token, { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ grant_type: "refresh_token", refresh_token: value.refresh, client_id: clientId }), ...(signal ? { signal } : {}) }); return withAccount(credential(body, value.refresh)); }
async function browser(interaction: Parameters<OAuthAuth["login"]>[0]): Promise<OAuthCredential> { const pkce = await generatePKCE(); const state = crypto.randomUUID(); const url = new URL(authorize); for (const [name, value] of Object.entries({ response_type: "code", client_id: clientId, redirect_uri: browserRedirect, scope, code_challenge: pkce.challenge, code_challenge_method: "S256", state, id_token_add_organizations: "true", codex_cli_simplified_flow: "true", originator: "rigyn" })) url.searchParams.set(name, value); interaction.notify({ type: "auth_url", url: url.href, instructions: "Complete sign-in, then paste the final redirect URL or authorization code." }); const parsed = authorizationInput(await interaction.prompt({ type: "manual_code", message: "Paste the authorization code or redirect URL:", placeholder: browserRedirect, ...(interaction.signal ? { signal: interaction.signal } : {}) })); if (!parsed.code) throw new Error("Missing authorization code"); if (parsed.state && parsed.state !== state) throw new Error("OAuth state mismatch"); return exchange(parsed.code, pkce.verifier, browserRedirect, interaction.signal); }
async function device(interaction: Parameters<OAuthAuth["login"]>[0]): Promise<OAuthCredential> { const started = await requestJson(deviceStart, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ client_id: clientId }), ...(interaction.signal ? { signal: interaction.signal } : {}) }); const deviceAuthId = required(started.body, "device_auth_id"); const userCode = required(started.body, "user_code"); const interval = typeof started.body.interval === "number" ? started.body.interval : Number(started.body.interval ?? 5); interaction.notify({ type: "device_code", userCode, verificationUri: `${base}/codex/device`, intervalSeconds: Number.isFinite(interval) ? interval : 5, expiresInSeconds: 900 }); const authorization = await pollOAuthDeviceCodeFlow<{ code: string; verifier: string }>({ intervalSeconds: Number.isFinite(interval) ? interval : 5, expiresInSeconds: 900, ...(interaction.signal ? { signal: interaction.signal } : {}), async poll() { const response = await fetch(devicePoll, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ device_auth_id: deviceAuthId, user_code: userCode }), ...(interaction.signal ? { signal: interaction.signal } : {}) }); if (response.ok) { const body = await response.json() as Record<string, unknown>; if (typeof body.authorization_code === "string" && typeof body.code_verifier === "string") return { status: "complete", value: { code: body.authorization_code, verifier: body.code_verifier } }; return { status: "failed", message: "Device token response omitted authorization fields" }; } const text = await response.text(); if (response.status === 403 || response.status === 404 || /authorization_pending/iu.test(text)) return { status: "pending" }; if (/slow_down/iu.test(text)) return { status: "slow_down" }; return { status: "failed", message: `Device authorization failed (${response.status}): ${text.slice(0, 2_000)}` }; } }); return exchange(authorization.code, authorization.verifier, deviceRedirect, interaction.signal); }
export const openaiCodexOAuth: OAuthAuth = { name: "OpenAI subscription", async login(interaction) { const method = await interaction.prompt({ type: "select", message: "Select login method:", options: [{ id: "browser", label: "Browser login" }, { id: "device", label: "Device code login", description: "For remote or headless systems" }], ...(interaction.signal ? { signal: interaction.signal } : {}) }); if (method === "device") return device(interaction); if (method === "browser") return browser(interaction); throw new Error(`Unknown login method: ${method}`); }, refresh, async toAuth(value) { const accountId = typeof value.accountId === "string" ? value.accountId : account(value.access); return { apiKey: value.access, ...(accountId ? { headers: { "chatgpt-account-id": accountId } } : {}) }; } };
