#!/usr/bin/env node

import { renameSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { ImagesModel } from "../src/types.ts";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const BASE_URL = "https://openrouter.ai/api/v1";
const MAX_CATALOG_BYTES = 8 * 1024 * 1024;

function record(value: unknown): Record<string, unknown> | undefined {
  return value !== null && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : undefined;
}

function modalities(value: unknown): Array<"text" | "image"> {
  return Array.isArray(value)
    ? [...new Set(value.filter((entry): entry is "text" | "image" => entry === "text" || entry === "image"))]
    : [];
}

function cost(value: unknown): number | undefined {
  if (value === undefined || value === null || value === "") return 0;
  if (typeof value !== "string" && typeof value !== "number") return undefined;
  const parsed = Number(value) * 1_000_000;
  return Number.isFinite(parsed) && parsed >= 0 ? parsed : undefined;
}

function parseModel(value: unknown): ImagesModel<"openrouter-images"> | undefined {
  const source = record(value);
  const architecture = record(source?.architecture);
  const pricing = record(source?.pricing);
  if (
    typeof source?.id !== "string" || source.id.length === 0 || Buffer.byteLength(source.id, "utf8") > 512 ||
    typeof source.name !== "string" || source.name.length === 0 || Buffer.byteLength(source.name, "utf8") > 2_048
  ) return undefined;
  const input = modalities(architecture?.input_modalities);
  const output = modalities(architecture?.output_modalities);
  if (!output.includes("image")) return undefined;
  if (input.length === 0) input.push("text");
  const rates = [cost(pricing?.prompt), cost(pricing?.completion), cost(pricing?.input_cache_read), cost(pricing?.input_cache_write)];
  if (!rates.every((rate): rate is number => rate !== undefined)) return undefined;
  return {
    id: source.id,
    name: source.name,
    api: "openrouter-images",
    provider: "openrouter",
    baseUrl: BASE_URL,
    input,
    output,
    cost: { input: rates[0], output: rates[1], cacheRead: rates[2], cacheWrite: rates[3] },
  };
}

export function parseOpenRouterImageModels(payload: unknown, strict: boolean): ImagesModel<"openrouter-images">[] {
  const data = record(payload)?.data;
  if (!Array.isArray(data) || data.length === 0) {
    if (strict) throw new Error("Image catalog returned a missing or empty image model list");
    return [];
  }
  const models = data.slice(0, 512).map(parseModel).filter((model): model is ImagesModel<"openrouter-images"> => model !== undefined);
  if (strict && models.length === 0) throw new Error("Image catalog returned no usable image models");
  return models.sort((left, right) => left.id.localeCompare(right.id));
}

function readStrictOption(args: string[]): boolean {
  for (const arg of args) if (arg !== "--strict") throw new Error(`Unknown argument: ${arg}`);
  return args.includes("--strict");
}

function render(models: readonly ImagesModel<"openrouter-images">[]): string {
  const values = models.map((model) => JSON.stringify(model)).join(",\n");
  return `// Generated by packages/models/scripts/generate-image-models.ts. Do not edit.
import type { ImagesApi, ImagesModel } from "./types.js";

const MODELS = [
${values},
] as unknown as ImagesModel<ImagesApi>[];

export const BUILTIN_IMAGE_MODEL_CATALOG: readonly ImagesModel<ImagesApi>[] = Object.freeze(MODELS);
export const IMAGE_MODELS = Object.freeze({ openrouter: Object.freeze(Object.fromEntries(MODELS.map((model) => [model.id, model]))) });
`;
}

async function fetchCatalog(strict: boolean): Promise<ImagesModel<"openrouter-images">[]> {
  const response = await fetch(`${BASE_URL}/models?output_modalities=image`, { redirect: "error" });
  if (!response.ok) throw new Error(`Image catalog request failed with HTTP ${response.status}`);
  const declared = Number(response.headers.get("content-length"));
  if (Number.isFinite(declared) && declared > MAX_CATALOG_BYTES) throw new Error("Image catalog response is too large");
  const text = await response.text();
  if (Buffer.byteLength(text, "utf8") > MAX_CATALOG_BYTES) throw new Error("Image catalog response is too large");
  return parseOpenRouterImageModels(JSON.parse(text), strict);
}

async function main(args: string[]): Promise<void> {
  const strict = readStrictOption(args);
  const models = await fetchCatalog(strict);
  const output = join(packageRoot, "src", "image-models.generated.ts");
  const staged = `${output}.${process.pid}.tmp`;
  try {
    writeFileSync(staged, render(models), "utf8");
    renameSync(staged, output);
  } finally {
    rmSync(staged, { force: true });
  }
  process.stdout.write(`Generated ${models.length} image models.\n`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2)).catch((error) => {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exitCode = 1;
  });
}
