// Generated by scripts/generate-provider-models.mjs from rigyn's maintained catalog. Do not edit.
import values from "./data/anthropic.json" with { type: "json" };
import type { Model } from "../types.js";

export const ANTHROPIC_MODELS = Object.freeze(values) as Readonly<{
  "claude-fable-5": Model<"anthropic-messages"> & {
    id: "claude-fable-5";
    provider: "anthropic";
  };
  "claude-haiku-4-5": Model<"anthropic-messages"> & {
    id: "claude-haiku-4-5";
    provider: "anthropic";
  };
  "claude-haiku-4-5-20251001": Model<"anthropic-messages"> & {
    id: "claude-haiku-4-5-20251001";
    provider: "anthropic";
  };
  "claude-opus-4-8": Model<"anthropic-messages"> & {
    id: "claude-opus-4-8";
    provider: "anthropic";
  };
}>;
