// Generated by scripts/generate-provider-models.mjs from rigyn's maintained catalog. Do not edit.
import values from "./data/azure-openai-responses.json" with { type: "json" };
import type { Model } from "../types.js";

export const AZURE_OPENAI_RESPONSES_MODELS = Object.freeze(values) as Readonly<{

}>;
