// Generated by scripts/generate-provider-models.mjs from Rigyn's maintained catalog. Do not edit.
import values from "./data/cloudflare-workers-ai.json" with { type: "json" };
import type { Model } from "../types.js";

export const CLOUDFLARE_WORKERS_AI_MODELS = Object.freeze(values) as Readonly<{

}>;
