// Generated by scripts/generate-provider-models.mjs from rigyn's maintained catalog. Do not edit.
import values from "./data/huggingface.json" with { type: "json" };
import type { Model } from "../types.js";

export const HUGGINGFACE_MODELS = Object.freeze(values) as Readonly<{

}>;
