// Generated by scripts/generate-provider-models.mjs from Rigyn's maintained catalog. Do not edit.
import values from "./data/minimax-cn.json" with { type: "json" };
import type { Model } from "../types.js";

export const MINIMAX_CN_MODELS = Object.freeze(values) as Readonly<{

}>;
