// Generated by scripts/generate-provider-models.mjs from Rigyn's maintained catalog. Do not edit.
import values from "./data/opencode-go.json" with { type: "json" };
import type { Model } from "../types.js";

export const OPENCODE_GO_MODELS = Object.freeze(values) as Readonly<{

}>;
