// Generated by scripts/generate-provider-models.mjs from rigyn's maintained catalog. Do not edit.
import values from "./data/opencode.json" with { type: "json" };
import type { Model } from "../types.js";

export const OPENCODE_MODELS = Object.freeze(values) as Readonly<{

}>;
