// Generated by scripts/generate-provider-models.mjs from rigyn's maintained catalog. Do not edit.
import values from "./data/openai.json" with { type: "json" };
import type { Model } from "../types.js";

export const OPENAI_MODELS = Object.freeze(values) as Readonly<{
  "gpt-5.4": Model<"openai-responses"> & {
    id: "gpt-5.4";
    provider: "openai";
  };
  "gpt-5.4-mini": Model<"openai-responses"> & {
    id: "gpt-5.4-mini";
    provider: "openai";
  };
  "gpt-5.4-nano": Model<"openai-responses"> & {
    id: "gpt-5.4-nano";
    provider: "openai";
  };
  "gpt-5.6": Model<"openai-responses"> & {
    id: "gpt-5.6";
    provider: "openai";
  };
  "gpt-5.6-luna": Model<"openai-responses"> & {
    id: "gpt-5.6-luna";
    provider: "openai";
  };
  "gpt-5.6-sol": Model<"openai-responses"> & {
    id: "gpt-5.6-sol";
    provider: "openai";
  };
  "gpt-5.6-terra": Model<"openai-responses"> & {
    id: "gpt-5.6-terra";
    provider: "openai";
  };
}>;
