// Generated by scripts/generate-provider-models.mjs from rigyn's maintained catalog. Do not edit.
import values from "./data/qwen-token-plan.json" with { type: "json" };
import type { Model } from "../types.js";

export const QWEN_TOKEN_PLAN_MODELS = Object.freeze(values) as Readonly<{

}>;
