// Generated by scripts/generate-provider-models.mjs from rigyn's maintained catalog. Do not edit.
import values from "./data/vercel-ai-gateway.json" with { type: "json" };
import type { Model } from "../types.js";

export const VERCEL_AI_GATEWAY_MODELS = Object.freeze(values) as Readonly<{

}>;
