// Generated by scripts/generate-provider-models.mjs from Rigyn's maintained catalog. Do not edit.
import values from "./data/xiaomi-token-plan-cn.json" with { type: "json" };
import type { Model } from "../types.js";

export const XIAOMI_TOKEN_PLAN_CN_MODELS = Object.freeze(values) as Readonly<{

}>;
