// Generated by scripts/generate-provider-models.mjs from rigyn's maintained catalog. Do not edit.
import values from "./data/xiaomi-token-plan-sgp.json" with { type: "json" };
import type { Model } from "../types.js";

export const XIAOMI_TOKEN_PLAN_SGP_MODELS = Object.freeze(values) as Readonly<{

}>;
