export { detectTerminalCapabilities, detectTerminalProtocols, terminalSize } from "./capabilities.js";
export {
  DEFAULT_RUNTIME_UI_MAX_BYTES,
  DEFAULT_RUNTIME_UI_MAX_LINES,
  DEFAULT_RUNTIME_UI_MAX_SPANS_PER_LINE,
  RuntimeUiComponentMount,
  runtimeUiKeyEvent,
  sanitizeRuntimeUiBlock,
  sanitizeRuntimeUiRenderContext,
  type RuntimeUiBlock,
  type RuntimeUiBlockLimits,
  type RuntimeUiComponent,
  type RuntimeUiComponentFactory,
  type RuntimeUiComponentHandle,
  type RuntimeUiComponentHost,
  type RuntimeUiComponentMountOptions,
  type RuntimeUiCustomOptions,
  type RuntimeUiKeyEvent,
  type RuntimeUiLine,
  type RuntimeUiOverlayAnchor,
  type RuntimeUiOverlayHandle,
  type RuntimeUiOverlayLength,
  type RuntimeUiOverlayMargin,
  type RuntimeUiOverlayOptions,
  type RuntimeUiOverlayUnfocusOptions,
  type RuntimeUiRenderContext,
  type RuntimeUiRenderResult,
  type RuntimeUiSpan,
  type RuntimeEditorRenderer,
  type RuntimeEditorRendererBinding,
  type RuntimeEditorRenderView,
  type RuntimeToolRenderer,
  type RuntimeToolRendererBinding,
  type RuntimeToolRenderView,
  type RuntimeSessionRendererBinding,
} from "./components.js";
export {
  uiMarkdown,
  uiPanel,
  uiStack,
  uiText,
  type RuntimeUiMarkdownOptions,
  type RuntimeUiPanelOptions,
  type RuntimeUiStackOptions,
  type RuntimeUiTextOptions,
  type RuntimeUiView,
} from "./component-kit.js";
export { TuiController, TuiSelectionCancelledError, DEFAULT_TUI_LIMITS } from "./controller.js";
export { createInteractiveDirectUiContext } from "./direct-ui.js";
export type { ReadonlyFooterDataProvider } from "./footer-data.js";
export {
  MultilineEditor,
  type EditorOptions as MultilineEditorOptions,
  type EditorPasteSnapshot,
  type EditorSnapshot,
  type TuiEditorImplementation,
} from "./editor.js";
export { editTextExternally, parseEditorCommand } from "./external-editor.js";
export { fuzzyScore, rankPickerItems } from "./fuzzy.js";
export { fuzzyFilter, fuzzyMatch, type FuzzyMatch } from "@rigyn/terminal";
export { KeyDecoder, type KeyEvent, type TerminalReply } from "./keys.js";
export {
  DEFAULT_KEYBINDINGS,
  KEYBINDING_ACTIONS,
  Keybindings as ConfiguredKeybindings,
  keybindingForEvent,
  loadKeybindings,
  normalizeKeybinding,
  parseKeybindings,
  type AppKeybindings,
  type KeybindingAction,
  type KeybindingOverrides,
} from "./keybindings.js";
export {
  getKeybindings,
  KeybindingsManager,
  setKeybindings,
  TUI_KEYBINDINGS,
  type Keybinding,
  type KeybindingConflict,
  type KeybindingDefinition,
  type KeybindingDefinitions,
  type KeybindingsConfig,
  type Keybindings,
} from "@rigyn/terminal";
export {
  decodeKittyPrintable,
  decodePrintableKey,
  isKeyRelease,
  isKeyRepeat,
  isKittyProtocolActive,
  Key,
  matchesKey,
  parseKey,
  setKittyProtocolActive,
  type KeyEventType,
  type KeyId,
} from "@rigyn/terminal";
export { renderFrame, renderTranscript, renderTranscriptFrame, pickerItem, type TranscriptRenderOptions } from "./layout.js";
export {
  buildSessionPickerRows,
  formatSessionAge,
  type SessionPickerOptions,
  type SessionPickerRow,
  type SessionPickerSortMode,
  type SessionPickerTimestamp,
} from "./session-picker.js";
export {
  buildSessionTreePickerRows,
  SESSION_TREE_FILTER_MODES,
  sessionTreeEndpointIndex,
  type SessionTreeFilterMode,
  type SessionTreePickerOptions,
} from "./session-tree-picker.js";
export { TuiModel } from "./model.js";
export {
  createNativeUiHost,
  createUnsafeTerminalHost,
  type NativeUiAutocompleteWrapper,
  type NativeUiControllerBridge,
  type NativeUiDisposer,
  type NativeUiEditorWrapper,
  type NativeUiHost,
  type NativeUiInputHandler,
  type NativeUiInputResult,
  type UnsafeTerminalHost,
  type UnsafeTerminalInputHandler,
  type UnsafeTerminalInputResult,
} from "./native-ui.js";
export {
  CombinedAutocompleteProvider,
  type AutocompleteItem,
  type AutocompleteProvider,
  type AutocompleteSuggestions,
  type SlashCommand,
} from "@rigyn/terminal";
export {
  Box,
  CancellableLoader,
  Editor,
  Image,
  Input,
  Loader,
  Markdown,
  SelectList,
  SettingsList,
  Spacer,
  Text,
  TruncatedText,
  type DefaultTextStyle,
  type EditorComponent,
  type EditorOptions,
  type EditorTheme,
  type ImageOptions,
  type ImageTheme,
  type LoaderIndicatorOptions,
  type MarkdownOptions,
  type MarkdownTheme,
  type SelectItem,
  type SelectListLayoutOptions,
  type SelectListTheme,
  type SelectListTruncatePrimaryContext,
  type SettingItem,
  type SettingsListOptions,
  type SettingsListTheme,
} from "@rigyn/terminal";
export {
  Container,
  CURSOR_MARKER,
  isFocusable,
  TUI,
  type Component,
  type Focusable,
  type OverlayAnchor,
  type OverlayHandle,
  type OverlayMargin,
  type OverlayOptions,
  type OverlayUnfocusOptions,
  type SizeValue,
} from "@rigyn/terminal";
export { ProcessTerminal, type ProcessTerminalOptions, type Terminal } from "@rigyn/terminal";
export { StdinBuffer, type StdinBufferEventMap, type StdinBufferOptions } from "@rigyn/terminal";
export {
  allocateImageId,
  calculateImageCellSize,
  calculateImageRows,
  deleteAllKittyImages,
  detectCapabilities,
  encodeITerm2,
  encodeKitty,
  getCapabilities,
  getCellDimensions,
  getGifDimensions,
  getImageDimensions,
  getJpegDimensions,
  getPngDimensions,
  getWebpDimensions,
  hyperlink,
  imageFallback,
  isImageLine,
  renderImage,
  resetCapabilitiesCache,
  setCapabilities,
  setCellDimensions,
  type CellDimensions,
  type ImageCellSize,
  type ImageDimensions,
  type ImageProtocol,
  type ImageRenderOptions,
  type TerminalCapabilities,
} from "@rigyn/terminal";
export {
  DEFAULT_TERMINAL_CELL_DIMENSIONS,
  ITERM_IMAGE_CHUNK_BYTES,
  KITTY_IMAGE_CHUNK_BYTES,
  MAX_TERMINAL_IMAGE_AGGREGATE_BYTES,
  MAX_TERMINAL_IMAGE_CHUNKS,
  MAX_TERMINAL_IMAGE_COUNT,
  TerminalImageRegistry,
  allocateTerminalImageId,
  calculateTerminalImageCells,
  composeTerminalImageOutput,
  deleteKittyImage,
  encodeITerm2Image,
  encodeKittyImage,
  encodeTerminalImage,
  terminalImageFallback,
  trustedHyperlinkTarget,
  trustedTerminalHyperlink,
  validateTerminalImage,
  validateTerminalImagePlacement,
  type TerminalCellDimensions,
  type TerminalImagePlacement,
  type TerminalImageProtocol,
  type TerminalImageResolution,
  type TranscriptImage,
  type ValidatedTerminalImage,
} from "./terminal-image.js";
export {
  createTheme,
  parseAutomaticThemePair,
  parseThemeDefinition,
  resolveThemeSetting,
  style,
  themeContrastDiagnostics,
  THEME_ROLES,
  THEME_SCHEMA_URI,
  THEME_TOKENS,
  type Theme,
  type AutomaticThemePair,
  type ThemeColorValue,
  type ThemeContrastDiagnostic,
  type ThemeDefinition,
  type ThemeExportDefinition,
  type ThemeRole,
  type ThemeStyleDefinition,
  type ThemeToken,
} from "./theme.js";
export {
  parseTerminalBackgroundReply,
  parseTerminalColorSchemeReply,
  terminalColorSchemeForRgb,
  terminalColorSchemeFromEnvironment,
  type TerminalColorScheme,
  type TerminalRgbColor,
} from "./terminal-colors.js";
export {
  isOsc11BackgroundColorResponse,
  parseOsc11BackgroundColor,
  parseTerminalColorSchemeReport,
  type RgbColor,
} from "@rigyn/terminal";
export { fileReferenceQuery, scanWorkspaceFiles, type WorkspaceFileScanOptions } from "./workspace-files.js";
export {
  byteTruncate,
  cellWidth,
  graphemeWidth,
  padCells,
  sanitizeTerminalText,
  splitGraphemes,
  stripAnsi,
  truncateCells,
  wrapCells,
} from "./unicode.js";
export { sliceByColumn, truncateToWidth, visibleWidth, wrapTextWithAnsi } from "@rigyn/terminal";
export type {
  EventRenderer,
  BuiltinThemeName,
  Frame,
  PickerCatalog,
  PickerItem,
  PickerKind,
  QueuedMessage,
  ScopedModelOption,
  ScopedModelSelection,
  SessionPickerMetadata,
  SessionTreeMetadata,
  TerminalCapabilities as ControllerTerminalCapabilities,
  TerminalChoice,
  ThemeName,
  TranscriptEntry,
  TuiAction,
  TuiAutocompleteCompletion,
  TuiAutocompleteProvider,
  TuiCommandArgumentCompletion,
  TuiCommandCompletionProvider,
  TuiContext,
  TuiControllerOptions,
  TuiEditorMiddleware,
  TuiEditorMiddlewareEvent,
  TuiEditorMiddlewareResult,
  TuiEditorMiddlewareSnapshot,
  TuiExtensionShortcut,
  TuiInput,
  TuiInputImageAttachment,
  TuiInputImageSummary,
  TuiLimits,
  TuiMode,
  TuiNormalizedKeyObserver,
  TuiOperatorPreferences,
  TuiOutput,
  TuiPersistentComponentSlot,
  TuiSignalSource,
  TuiSettingItem,
  TuiThemeChange,
  TuiViewState,
  TuiWorkingIndicatorOptions,
} from "./types.js";
export * from "./public-theme.js";
export * from "./public-components.js";
