#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const BASE_URL = "https://openrouter.ai/api/v1";
const OUTPUT = resolve(dirname(fileURLToPath(import.meta.url)), "../src/images/models.generated.ts");
const MAX_CATALOG_BYTES = 8 * 1024 * 1024;

interface CatalogModel {
  id: string;
  name: string;
  architecture?: {
    input_modalities?: unknown;
    output_modalities?: unknown;
  };
  pricing?: {
    prompt?: unknown;
    completion?: unknown;
    input_cache_read?: unknown;
    input_cache_write?: unknown;
  };
}

interface GeneratedModel {
  id: string;
  name: string;
  input: Array<"text" | "image">;
  output: Array<"text" | "image">;
  pricing?: { input: number; output: number; cacheRead: number; cacheWrite: number };
}

function record(value: unknown): Record<string, unknown> | undefined {
  return value !== null && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : undefined;
}

function modalities(value: unknown): Array<"text" | "image"> {
  if (!Array.isArray(value)) return [];
  return [...new Set(value.filter((entry): entry is "text" | "image" => entry === "text" || entry === "image"))];
}

function price(value: unknown): number | undefined {
  if (typeof value !== "string" && typeof value !== "number") return 0;
  const parsed = Number(value) * 1_000_000;
  return Number.isFinite(parsed) && parsed >= 0 ? parsed : undefined;
}

function parseModel(value: unknown): GeneratedModel | undefined {
  const source = record(value) as CatalogModel | undefined;
  if (
    source === undefined ||
    typeof source.id !== "string" ||
    typeof source.name !== "string" ||
    source.id === "" ||
    Buffer.byteLength(source.id, "utf8") > 512 ||
    Buffer.byteLength(source.name, "utf8") > 2_048
  ) return undefined;
  const input = modalities(source.architecture?.input_modalities);
  const output = modalities(source.architecture?.output_modalities);
  if (!output.includes("image")) return undefined;
  if (input.length === 0) input.push("text");
  const prices = [
    price(source.pricing?.prompt),
    price(source.pricing?.completion),
    price(source.pricing?.input_cache_read),
    price(source.pricing?.input_cache_write),
  ];
  const pricing = prices.every((entry): entry is number => entry !== undefined)
    ? { input: prices[0]!, output: prices[1]!, cacheRead: prices[2]!, cacheWrite: prices[3]! }
    : undefined;
  return { id: source.id, name: source.name, input, output, ...(pricing === undefined ? {} : { pricing }) };
}

async function catalog(): Promise<GeneratedModel[]> {
  const response = await fetch(`${BASE_URL}/models?output_modalities=image`, { redirect: "error" });
  if (!response.ok) throw new Error(`Image catalog request failed with HTTP ${response.status}`);
  const declared = Number(response.headers.get("content-length"));
  if (Number.isFinite(declared) && declared > MAX_CATALOG_BYTES) throw new Error("Image catalog response is too large");
  const text = await response.text();
  if (Buffer.byteLength(text, "utf8") > MAX_CATALOG_BYTES) throw new Error("Image catalog response is too large");
  const data = record(JSON.parse(text))?.data;
  if (!Array.isArray(data)) throw new Error("Image catalog response did not contain a model array");
  const models = data.slice(0, 512).map(parseModel).filter((entry): entry is GeneratedModel => entry !== undefined);
  if (models.length === 0) throw new Error("Image catalog did not contain any usable image models");
  return models.sort((left, right) => left.id.localeCompare(right.id));
}

function source(models: readonly GeneratedModel[]): string {
  const entries = models.map((entry) => `  {
    id: ${JSON.stringify(entry.id)},
    name: ${JSON.stringify(entry.name)},
    api: "openrouter-images",
    provider: "openrouter",
    baseUrl: ${JSON.stringify(BASE_URL)},
    input: ${JSON.stringify(entry.input)},
    output: ${JSON.stringify(entry.output)},${entry.pricing === undefined ? "" : `
    pricing: ${JSON.stringify(entry.pricing)},`}
  },`).join("\n");
  return `// Generated by scripts/generate-image-models.ts. Do not edit by hand.
import type { ImagesModel } from "./types.js";

export const OPENROUTER_IMAGE_MODELS = [
${entries}
] as const satisfies readonly ImagesModel<"openrouter-images">[];
`;
}

const models = await catalog();
await writeFile(OUTPUT, source(models), "utf8");
process.stdout.write(`Generated ${models.length} image models at ${OUTPUT}\n`);
