import { anthropicMessagesApi } from "./api/anthropic-messages.lazy.js";
import type { AnthropicOptions } from "./api/anthropic-messages.js";
import { azureOpenAIResponsesApi } from "./api/azure-openai-responses.lazy.js";
import type { AzureOpenAIResponsesOptions } from "./api/azure-openai-responses.js";
import { googleGenerativeAIApi } from "./api/google-generative-ai.lazy.js";
import type { GoogleOptions } from "./api/google-generative-ai.js";
import { googleVertexApi } from "./api/google-vertex.lazy.js";
import type { GoogleVertexOptions } from "./api/google-vertex.js";
import { mistralConversationsApi } from "./api/mistral-conversations.lazy.js";
import type { MistralOptions } from "./api/mistral-conversations.js";
import { openAICodexResponsesApi } from "./api/openai-codex-responses.lazy.js";
import type { OpenAICodexResponsesOptions } from "./api/openai-codex-responses.js";
import { openAICompletionsApi } from "./api/openai-completions.lazy.js";
import type { OpenAICompletionsOptions } from "./api/openai-completions.js";
import { openAIResponsesApi } from "./api/openai-responses.lazy.js";
import type { OpenAIResponsesOptions } from "./api/openai-responses.js";
import type { SimpleStreamOptions, StreamFunction } from "./types.js";

const anthropic = anthropicMessagesApi();
const azure = azureOpenAIResponsesApi();
const google = googleGenerativeAIApi();
const vertex = googleVertexApi();
const mistral = mistralConversationsApi();
const codex = openAICodexResponsesApi();
const completions = openAICompletionsApi();
const responses = openAIResponsesApi();

export const streamAnthropic = anthropic.stream as StreamFunction<"anthropic-messages", AnthropicOptions>;
export const streamSimpleAnthropic = anthropic.streamSimple as StreamFunction<"anthropic-messages", SimpleStreamOptions>;
export const streamAzureOpenAIResponses = azure.stream as StreamFunction<"azure-openai-responses", AzureOpenAIResponsesOptions>;
export const streamSimpleAzureOpenAIResponses = azure.streamSimple as StreamFunction<"azure-openai-responses", SimpleStreamOptions>;
export const streamGoogle = google.stream as StreamFunction<"google-generative-ai", GoogleOptions>;
export const streamSimpleGoogle = google.streamSimple as StreamFunction<"google-generative-ai", SimpleStreamOptions>;
export const streamGoogleVertex = vertex.stream as StreamFunction<"google-vertex", GoogleVertexOptions>;
export const streamSimpleGoogleVertex = vertex.streamSimple as StreamFunction<"google-vertex", SimpleStreamOptions>;
export const streamMistral = mistral.stream as StreamFunction<"mistral-conversations", MistralOptions>;
export const streamSimpleMistral = mistral.streamSimple as StreamFunction<"mistral-conversations", SimpleStreamOptions>;
export const streamOpenAICodexResponses = codex.stream as StreamFunction<"openai-codex-responses", OpenAICodexResponsesOptions>;
export const streamSimpleOpenAICodexResponses = codex.streamSimple as StreamFunction<"openai-codex-responses", SimpleStreamOptions>;
export const streamOpenAICompletions = completions.stream as StreamFunction<"openai-completions", OpenAICompletionsOptions>;
export const streamSimpleOpenAICompletions = completions.streamSimple as StreamFunction<"openai-completions", SimpleStreamOptions>;
export const streamOpenAIResponses = responses.stream as StreamFunction<"openai-responses", OpenAIResponsesOptions>;
export const streamSimpleOpenAIResponses = responses.streamSimple as StreamFunction<"openai-responses", SimpleStreamOptions>;
